# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    prefix-development: ci
    include: scope

- package-ecosystem: maven
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: deps
    prefix-development: chore
    include: scope
  labels:
    - dependencies
