# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: License check

on:
  push:
    branches-ignore: # build all branches except:
      - 'dependabot/**' # prevent GHA triggered twice (once for commit to the branch and once for opening/syncing the PR)
    tags-ignore: # don't build tags
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      dash-iplab-token:
        description: "Gitlab Personal Access Token (https://gitlab.eclipse.org/-/profile/personal_access_tokens) with 'api'' scope for Automatic IP Team Review Requests via org.eclipse.dash:license-tool-plugin, see https://github.com/eclipse/dash-licenses#automatic-ip-team-review-requests"
        default: ""
        type: string

defaults:
  run:
    shell: bash

env:
  JAVA_VERSION: 17

jobs:

  license_check:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4 #https://github.com/actions/checkout

    - name: "Install: JDK ${{ env.JAVA_VERSION }}"
      uses: actions/setup-java@v4 # https://github.com/actions/setup-java
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: "Cache: Local Maven Repository"
      uses: actions/cache@v4
      with:
        # Excluded sub directory not working https://github.com/actions/cache/issues/494#issuecomment-948783891
        path: |
          ~/.m2/repository/*
          !~/.m2/repository/.cache/tycho
          !~/.m2/repository/.meta/p2-artifacts.properties
          !~/.m2/repository/p2
          !~/.m2/repository/*SNAPSHOT*
        key: ${{ runner.os }}-repo-mvn-${{ hashFiles('**/pom.xml') }}

    - name: "Cache: Local Tycho Repository"
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository/.cache/tycho
          ~/.m2/repository/.meta/p2-artifacts.properties
          ~/.m2/repository/p2
        key: ${{ runner.os }}-repo-tycho-${{ hashFiles('target-platforms/oldest.target') }}

    - name: "Install: Maven"
      uses: stCarolas/setup-maven@v4.5 # https://github.com/stCarolas/setup-maven
      with:
        maven-version: 3.9.6

    - name: Dash License check # see https://github.com/eclipse/dash-licenses
      env:
        DASH_IPLAB_TOKEN: "${{ inputs.dash-iplab-token }}"
      run: |
        set -eu

        MAVEN_OPTS+=" -Djava.security.egd=file:/dev/./urandom" # https://stackoverflow.com/questions/58991966/what-java-security-egd-option-is-for/59097932#59097932
        MAVEN_OPTS+=" -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS" # https://stackoverflow.com/questions/5120470/how-to-time-the-different-stages-of-maven-execution/49494561#49494561
        MAVEN_OPTS+=" -Xmx1024m -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2"
        echo "  -> MAVEN_OPTS: $MAVEN_OPTS"
        export MAVEN_OPTS

        # "excludeArtifactIds" parameter is to prevent builds from failing with:
        # License information could not be automatically verified for the following content:
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.core/0.5.2-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.feature/0.5.4-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.language_pack.feature/0.1.1-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.language_pack/0.1.1-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.languageconfiguration/0.5.4-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.markdown/0.5.1-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.registry/0.6.3-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.samples/0.4.1-SNAPSHOT
        # maven/mavencentral/org.eclipse/org.eclipse.tm4e.ui/0.6.2-SNAPSHOT
        # p2/orbit/p2.p2.installable.unit/org.eclipse.rcp_root/4.24.0.v20220607-0700
        # p2/orbit/p2.eclipse.plugin/org.eclipse.ui.tests.harness/1.10.0.v20230220-1021
        # This content is either not correctly mapped by the system, or requires review.
        # Error: Dependency license check failed. Some dependencies need to be vetted. 

        mvn \
          --errors \
          --update-snapshots \
          --batch-mode \
          --show-version \
          --no-transfer-progress \
          -Dtycho.disableP2Mirrors=true \
          org.eclipse.dash:license-tool-plugin:license-check \
          -Dtycho.target.eager=true \
          -Ddash.projectId=technology.tm4e \
          -Ddash.iplab.token="$DASH_IPLAB_TOKEN" \
          -Ddash.fail=true \
          -Ddash.summary=DEPENDENCIES \
          -DexcludeArtifactIds=\
        org.eclipse.rcp_root,\
        org.eclipse.tm4e.core,\
        org.eclipse.tm4e.feature,\
        org.eclipse.tm4e.language_pack.feature,\
        org.eclipse.tm4e.language_pack,\
        org.eclipse.tm4e.languageconfiguration,\
        org.eclipse.tm4e.markdown,\
        org.eclipse.tm4e.registry,\
        org.eclipse.tm4e.samples,\
        org.eclipse.tm4e.ui,\
        org.eclipse.ui.tests.harness

    - name: Dash Summary
      if: always()
      run: cat DEPENDENCIES
